export default {
  emptyString: '',
  containedBtnVariant: 'contained',
  outlinedBtnVariant: 'outlined',
  addBtnClass: 'toDoFormModal__add-btn',
  boxModalClass: 'toDoFormModal__box',
  modalTitleAriaLabelledby: 'modal-modal-title',
  modalDescriptionAriaDescribedby: 'modal-modal-description',
  formClass: 'toDoFormModal__form',
  textType: 'text',
  titleName: 'title',
  titleLabel: 'Title',
  inputClass: 'toDoFormModal__input',
  descriptionName: 'description',
  descriptionLabel: 'Description',
  statusName: 'status',
  statusLabel: 'Status',
  selectClass: 'toDoFormModal__select',
  priorityName: 'priority',
  priorityLabel: 'Priority',
  secondSpacing: 2,
  buttonsBoxClass: 'toDoFormModal__buttons-box',
  rowDirection: 'row',
  submitBtnType: 'submit',
};
