export const GET_GOODS_LIST_SUCCESS = 'GET_GOODS_LIST_SUCCESS';
export const GET_ONE_GOOD_SUCCESS = 'GET_ONE_GOOD_SUCCESS';
export const ADD_GOOD_SUCCESS = 'ADD_GOOD_SUCCESS';
export const EDIT_GOOD_SUCCESS = 'EDIT_GOOD_SUCCESS';

export const ACTION_REQUEST = 'ACTION_REQUEST';
export const ACTION_SUCCESS = 'ACTION_SUCCESS';
export const ACTION_FAILURE = 'ACTION_FAILURE';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SET_FILTER = 'SET_FILTER';
export const SET_SORT = 'SET_SORT';

export const CLOSE_FORM_MODAL = 'CLOSE_FORM_MODAL';
export const OPEN_FORM_MODAL = 'OPEN_FORM_MODAL';
