export default {
  tableContainerClass: 'table-container',
  tableClass: 'table',
  tableHeadClass: 'table-head',
  tableRowClass: 'table-row',
  tableCellClass: 'table-cell',
  tableBodyClass: 'table-body',
  buttonsBoxClass: 'goodsList__buttons-box',
  centerAlign: 'center',
  leftAlign: 'left',
  h4Variant: 'h4',
  h6Variant: 'h6',
  rowDirection: 'row',
  secondSpacing: '2',
  primaryColor: 'primary',
  successColor: 'success',
  errorColor: 'error',
  noGoodClass: 'goodList__noGood',
  titleColumnName: 'title',
  weightColumnName: 'weight',
  descriptionColumnName: 'description',
  categoryColumnName: 'category',
};
